"""The single-file PDF build: the mdast renderer behind scripts/build-pdf.py.

The renderer is the one place in this repository where the book's content passes through code that
is not MyST's. If it silently dropped a node type, the PDF would quietly be missing a paragraph and
nothing would say so — so the contract these tests pin down is that it fails loudly instead.
"""

import importlib.util
import sys
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parent.parent


def _load():
    """Import a script that is not a package module, and whose name has a hyphen in it."""
    spec = importlib.util.spec_from_file_location("build_pdf", ROOT / "scripts" / "build-pdf.py")
    module = importlib.util.module_from_spec(spec)
    sys.modules["build_pdf"] = module
    spec.loader.exec_module(module)
    return module


build_pdf = _load()


def text(value):
    return {"type": "text", "value": value}


def render(node, slug="ch07-continuous-batching"):
    return build_pdf.Renderer(slug).render(node)


# -- the contract that matters -----------------------------------------------------------


def test_an_unknown_node_is_an_error_not_a_silent_omission():
    with pytest.raises(build_pdf.UnknownNodeError, match="mystDirective"):
        render({"type": "mystDirective", "children": [text("invisible")]})


def test_every_node_type_the_book_uses_is_handled():
    """A tripwire for the day a chapter starts using a directive the renderer has not met."""
    for kind in (
        "text",
        "paragraph",
        "strong",
        "emphasis",
        "inlineCode",
        "heading",
        "list",
        "listItem",
        "link",
        "code",
        "table",
        "tableRow",
        "tableCell",
        "admonition",
        "admonitionTitle",
        "blockquote",
        "crossReference",
        "include",
        "comment",
        "block",
        "root",
    ):
        node = {"type": kind, "children": [text("x")], "value": "x"}
        if kind in {"tableRow", "tableCell", "admonitionTitle"}:
            continue  # only ever reached through their parent
        render(node)


# -- anchors and links --------------------------------------------------------------------


def test_headings_are_namespaced_by_page():
    """Every chapter has its own 'the-cost'; unqualified ids would all collide on chapter one."""
    node = {"type": "heading", "depth": 3, "html_id": "the-cost", "children": [text("The cost")]}
    assert 'id="ch07-continuous-batching--the-cost"' in render(node)


def test_a_reference_to_another_chapter_points_at_that_chapter():
    node = {
        "type": "crossReference",
        "url": "/ch09-prefix-caching",
        "html_id": "ch09",
        "children": [text("ch09")],
    }
    assert 'href="#ch09-prefix-caching--ch09"' in render(node)


def test_a_reference_within_a_page_stays_on_that_page():
    """A same-page reference carries no URL, so the current page is the only sensible target."""
    node = {"type": "crossReference", "html_id": "the-idea", "children": [text("above")]}
    assert 'href="#ch07-continuous-batching--the-idea"' in render(node)


# -- content ------------------------------------------------------------------------------


def test_code_keeps_its_filename_and_escapes_its_body():
    node = {"type": "code", "value": "a < b & c", "lang": "python", "filename": "router.py"}
    out = render(node)
    assert "<figcaption>router.py</figcaption>" in out
    assert "a &lt; b &amp; c" in out
    assert "language-python" in out


def test_an_empty_header_row_is_dropped():
    """The chapter-header grids are written with no column headings; an empty band reads as a bug."""
    empty = {"type": "tableCell", "header": True, "children": []}
    filled = {"type": "tableCell", "children": [text("Tier 1")]}
    node = {
        "type": "table",
        "children": [
            {"type": "tableRow", "children": [empty, dict(empty)]},
            {"type": "tableRow", "children": [filled]},
        ],
    }
    out = render(node)
    assert "<thead>" not in out
    assert "Tier 1" in out


def test_a_real_header_row_is_kept():
    header = {"type": "tableCell", "header": True, "children": [text("Policy")]}
    body = {"type": "tableCell", "children": [text("Round-robin")]}
    node = {
        "type": "table",
        "children": [
            {"type": "tableRow", "children": [header]},
            {"type": "tableRow", "children": [body]},
        ],
    }
    out = render(node)
    assert "<thead><tr><th>Policy</th></tr></thead>" in out
    assert "<tbody><tr><td>Round-robin</td></tr></tbody>" in out


def test_the_do_not_edit_banner_on_a_generated_fragment_is_not_printed():
    assert render({"type": "comment", "value": "Generated by scripts/render-scorecards.py"}) == ""


def test_an_admonition_keeps_its_kind_and_title():
    node = {
        "type": "admonition",
        "kind": "warning",
        "children": [
            {"type": "admonitionTitle", "children": [text("What this rig cannot tell you")]},
            {"type": "paragraph", "children": [text("Four replicas share one CPU.")]},
        ],
    }
    out = render(node)
    assert 'class="admonition warning"' in out
    assert "What this rig cannot tell you" in out
    assert "<p>Four replicas share one CPU.</p>" in out


def test_text_is_escaped_so_prose_cannot_inject_markup():
    assert render(text("a < b")) == "a &lt; b"


# -- structure ----------------------------------------------------------------------------


def test_the_chapter_order_comes_from_the_table_of_contents():
    """The PDF must not invent an order of its own, or it stops matching the website."""
    pages = build_pdf.load_pages()
    front, parts = build_pdf.load_structure(pages)
    assert front is not None and front.slug == "index"
    assert [part.title for part in parts][0].startswith("Part I")
    assert sum(len(part.pages) for part in parts) == 34
    assert parts[0].pages[0].slug.startswith("ch01")


def test_titles_are_plain_text_for_the_contents_list():
    assert build_pdf.strip_tags("<strong>ch18</strong> &middot; Routing") == "ch18 · Routing"
