"""The single-file PDF build: the mdast renderer behind scripts/build-pdf.py.

The renderer is the one place in this repository where the book's content passes through code that
is not MyST's. If it silently dropped a node type, the PDF would quietly be missing a paragraph and
nothing would say so — so the contract these tests pin down is that it fails loudly instead.
"""

import importlib.util
import re
import sys
from pathlib import Path

import pytest
import yaml

ROOT = Path(__file__).resolve().parent.parent


def _load():
    """Import a script that is not a package module, and whose name has a hyphen in it."""
    spec = importlib.util.spec_from_file_location("build_pdf", ROOT / "scripts" / "build-pdf.py")
    module = importlib.util.module_from_spec(spec)
    sys.modules["build_pdf"] = module
    spec.loader.exec_module(module)
    return module


build_pdf = _load()


def text(value):
    return {"type": "text", "value": value}


def render(node, slug="ch07-continuous-batching"):
    return build_pdf.Renderer(slug).render(node)


# -- the contract that matters -----------------------------------------------------------


def test_an_unknown_node_is_an_error_not_a_silent_omission():
    with pytest.raises(build_pdf.UnknownNodeError, match="mystDirective"):
        render({"type": "mystDirective", "children": [text("invisible")]})


def test_every_node_type_the_book_uses_is_handled():
    """A tripwire for the day a chapter starts using a directive the renderer has not met."""
    for kind in (
        "text",
        "paragraph",
        "strong",
        "emphasis",
        "inlineCode",
        "heading",
        "list",
        "listItem",
        "link",
        "code",
        "table",
        "tableRow",
        "tableCell",
        "admonition",
        "admonitionTitle",
        "blockquote",
        "crossReference",
        "include",
        "comment",
        "block",
        "root",
    ):
        node = {"type": kind, "children": [text("x")], "value": "x"}
        if kind in {"tableRow", "tableCell", "admonitionTitle"}:
            continue  # only ever reached through their parent
        render(node)


# -- anchors and links --------------------------------------------------------------------


def test_headings_are_namespaced_by_page():
    """Every chapter has its own 'the-cost'; unqualified ids would all collide on chapter one."""
    node = {"type": "heading", "depth": 3, "html_id": "the-cost", "children": [text("The cost")]}
    assert 'id="ch07-continuous-batching--the-cost"' in render(node)


def test_a_reference_to_another_chapter_points_at_that_chapter():
    node = {
        "type": "crossReference",
        "url": "/ch09-prefix-caching",
        "html_id": "ch09",
        "children": [text("ch09")],
    }
    assert 'href="#ch09-prefix-caching--ch09"' in render(node)


def test_a_reference_within_a_page_stays_on_that_page():
    """A same-page reference carries no URL, so the current page is the only sensible target."""
    node = {"type": "crossReference", "html_id": "the-idea", "children": [text("above")]}
    assert 'href="#ch07-continuous-batching--the-idea"' in render(node)


# -- content ------------------------------------------------------------------------------


def test_code_keeps_its_filename_and_escapes_its_body():
    node = {"type": "code", "value": "a < b & c", "lang": "python", "filename": "router.py"}
    out = render(node)
    assert "<figcaption>router.py</figcaption>" in out
    assert "a &lt; b &amp; c" in out
    assert "language-python" in out


def test_an_empty_header_row_is_dropped():
    """The chapter-header grids are written with no column headings; an empty band reads as a bug."""
    empty = {"type": "tableCell", "header": True, "children": []}
    filled = {"type": "tableCell", "children": [text("Tier 1")]}
    node = {
        "type": "table",
        "children": [
            {"type": "tableRow", "children": [empty, dict(empty)]},
            {"type": "tableRow", "children": [filled]},
        ],
    }
    out = render(node)
    assert "<thead>" not in out
    assert "Tier 1" in out


def test_a_real_header_row_is_kept():
    header = {"type": "tableCell", "header": True, "children": [text("Policy")]}
    body = {"type": "tableCell", "children": [text("Round-robin")]}
    node = {
        "type": "table",
        "children": [
            {"type": "tableRow", "children": [header]},
            {"type": "tableRow", "children": [body]},
        ],
    }
    out = render(node)
    assert "<thead><tr><th>Policy</th></tr></thead>" in out
    assert "<tbody><tr><td>Round-robin</td></tr></tbody>" in out


def test_the_do_not_edit_banner_on_a_generated_fragment_is_not_printed():
    assert render({"type": "comment", "value": "Generated by scripts/render-scorecards.py"}) == ""


def test_an_admonition_keeps_its_kind_and_title():
    node = {
        "type": "admonition",
        "kind": "warning",
        "children": [
            {"type": "admonitionTitle", "children": [text("What this rig cannot tell you")]},
            {"type": "paragraph", "children": [text("Four replicas share one CPU.")]},
        ],
    }
    out = render(node)
    assert 'class="admonition warning"' in out
    assert "What this rig cannot tell you" in out
    assert "<p>Four replicas share one CPU.</p>" in out


def test_text_is_escaped_so_prose_cannot_inject_markup():
    assert render(text("a < b")) == "a &lt; b"


# -- structure ----------------------------------------------------------------------------


def toc_entries():
    """myst.yml's table of contents: the order the website publishes in, and so the PDF's order."""
    return yaml.safe_load((ROOT / "myst.yml").read_text())["project"]["toc"]


def parsed_pages(skip=()):
    """A stand-in for ``load_pages()``, covering every file myst.yml lists.

    The real ``load_pages`` reads a completed MyST build off disk, which these tests have no
    business requiring: a test that passes only when you happen to have built the site already is
    worse than no test, because it goes green locally and red in CI — which is exactly what this
    one did. What is worth pinning is the ordering logic, and that takes its pages as an argument.
    The end-to-end version of the check is the deploy workflow building the real PDF, where a page
    missing from the parse fails the deploy.

    ``slug`` here is the filename stem, which is *not* a claim about MyST's slugging rules — the
    assertions below are on ``source``, the one identifier myst.yml and MyST agree on.
    """
    pages = {}
    for entry in toc_entries():
        listed = (
            [entry["file"]]
            if "file" in entry
            else [child["file"] for child in entry.get("children") or [] if "file" in child]
        )
        for source in listed:
            source = source.lstrip("./")
            if source in skip:
                continue
            pages[source] = build_pdf.Page(
                slug=Path(source).stem,
                source=source,
                mdast={"type": "root", "children": []},
            )
    return pages


def test_the_chapter_order_comes_from_the_table_of_contents():
    """The PDF must not invent an order of its own, or it stops matching the website."""
    front, parts = build_pdf.load_structure(parsed_pages())
    assert front is not None and front.source == "index.md"
    assert [part.title for part in parts][0].startswith("Part I")
    # Counted from the table of contents rather than hardcoded: this assertion exists to catch a
    # page the traversal *dropped*, and a literal would only catch the day somebody adds a chapter.
    listed = sum(len(entry.get("children") or []) for entry in toc_entries() if "title" in entry)
    assert sum(len(part.pages) for part in parts) == listed
    assert parts[0].pages[0].source.startswith("chapters/ch01")


def test_a_page_in_the_toc_that_was_not_parsed_is_an_error():
    """The assertion that actually catches a dropped chapter.

    A PDF quietly missing a chapter is indistinguishable from a complete one, so the only defence
    is refusing to write it at all.
    """
    dropped = next(source for source in parsed_pages() if source.startswith("chapters/"))
    with pytest.raises(SystemExit, match=re.escape(dropped)):
        build_pdf.load_structure(parsed_pages(skip={dropped}))


def test_the_progress_line_survives_an_output_path_outside_the_repository():
    """``--out`` accepts any path, and the run used to die at the line that reports success."""
    assert build_pdf.shown(ROOT / "_build" / "book.pdf") == Path("_build/book.pdf")
    # The two cases that used to raise: a path outside the repository, and a relative one — which
    # is what the deploy workflow passes, so this was a broken deploy waiting to happen.
    for path in (Path("/tmp/somewhere-else/book.pdf"), Path("_build/html/book.pdf")):
        assert build_pdf.shown(path) == path


def test_titles_are_plain_text_for_the_contents_list():
    assert build_pdf.strip_tags("<strong>ch20</strong> &middot; Routing") == "ch20 · Routing"
