#!/usr/bin/env python3
"""Render scorecard fragments from committed benchmark results.

Writes one markdown fragment per entry in ``bench.scorecards.SCORECARDS`` into
``chapters/_generated/``. Chapters include those fragments, so every figure in the book traces
back to a stamped result file (PLAN.md §6.3).

Usage:
    python3 scripts/render-scorecards.py            # write fragments
    python3 scripts/render-scorecards.py --check    # fail if any committed fragment is stale
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from bench.scorecard import (  # noqa: E402
    agent_cancellation_table,
    agent_chain_table,
    arithmetic_table,
    attention_footprint_table,
    break_even_table,
    chat_batch_table,
    chat_turn_table,
    chunk_cost_table,
    cold_start_table,
    completion_table,
    conditions,
    constrained_validity_table,
    cost_table,
    drain_table,
    fairness_table,
    final_scorecard_table,
    gather_cost_table,
    generator_table,
    handoff_table,
    instrumentation_cost_table,
    kv_quantisation_table,
    lora_batch_table,
    lora_memory_table,
    lora_quality_table,
    mask_cost_table,
    memory_table,
    offline_table,
    outlier_table,
    pipeline_bubble_table,
    quantisation_table,
    rag_interference_table,
    routing_table,
    score_matrix_table,
    shedding_table,
    signal_timing_table,
    speculation_distribution_table,
    speculation_table,
    table,
    template_reuse_table,
    tensor_parallel_table,
    workload_table,
)
from bench.scorecards import CONDITIONS, SCORECARDS  # noqa: E402

OUT_DIR = ROOT / "chapters" / "_generated"

BANNER = "<!-- Generated by scripts/render-scorecards.py. Do not edit by hand. -->"


#: fragments that are computed rather than tabulated from a single result set
DERIVED = {
    "ch03-arithmetic": lambda: arithmetic_table("cached-rate1-tier1", "naive-rate1-tier1"),
    "ch08-memory": memory_table,
    "ch10-chunk-cost": chunk_cost_table,
    "ch11-handoff": handoff_table,
    "ch12-footprint": attention_footprint_table,
    "ch12-score-matrix": score_matrix_table,
    "ch13-gather-cost": gather_cost_table,
    "ch14-quantisation": quantisation_table,
    "ch14-kv-quantisation": kv_quantisation_table,
    "ch14-outliers": outlier_table,
    "ch15-acceptance": speculation_table,
    "ch15-distribution": speculation_distribution_table,
    "ch16-validity": constrained_validity_table,
    "ch16-mask-cost": mask_cost_table,
    "ch17-collectives": tensor_parallel_table,
    "ch17-bubbles": pipeline_bubble_table,
    "ch18-routing": routing_table,
    "ch18-cold-start": cold_start_table,
    "ch19-adapter-memory": lora_memory_table,
    "ch19-quality": lora_quality_table,
    "ch19-batch": lora_batch_table,
    "ch19-fairness": fairness_table,
    "ch20-workloads": workload_table,
    "ch20-turns": chat_turn_table,
    "ch20-batch": chat_batch_table,
    "ch21-interference": rag_interference_table,
    "ch22-chains": agent_chain_table,
    "ch22-cancellation": agent_cancellation_table,
    "ch23-completion": completion_table,
    "ch23-offline": offline_table,
    "ch24-templates": template_reuse_table,
    "ch25-signals": signal_timing_table,
    "ch25-overhead": instrumentation_cost_table,
    "ch26-shedding": shedding_table,
    "ch26-drain": drain_table,
    "ch27-cost": cost_table,
    "ch27-break-even": break_even_table,
    "ch28-generators": generator_table,
    "ch29-journey": final_scorecard_table,
}


def render(name: str) -> str:
    body = DERIVED[name]() if name in DERIVED else table(SCORECARDS[name])
    parts = [BANNER, "", body]
    source = CONDITIONS.get(name)
    if source:
        parts += ["", f"*Conditions: {conditions(source)}*"]
    return "\n".join(parts) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="verify instead of writing")
    args = parser.parse_args()

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    stale: list[str] = []

    for name in sorted({**SCORECARDS, **DERIVED}):
        target = OUT_DIR / f"{name}.md"
        try:
            rendered = render(name)
        except FileNotFoundError as exc:
            print(f"  MISSING RESULT for {name}: {exc}")
            stale.append(name)
            continue

        if args.check:
            current = target.read_text() if target.exists() else ""
            if current != rendered:
                stale.append(name)
                print(f"  STALE: chapters/_generated/{name}.md")
        else:
            target.write_text(rendered)
            print(f"  wrote chapters/_generated/{name}.md")

    if args.check and stale:
        print(
            "\nrender-scorecards: FAILED — "
            f"{len(stale)} fragment(s) out of date. Run scripts/render-scorecards.py."
        )
        return 1
    print(f"\nrender-scorecards: OK ({len(SCORECARDS) + len(DERIVED)} fragment(s))")
    return 0


if __name__ == "__main__":
    sys.exit(main())
