#!/usr/bin/env python3
"""Render scorecard fragments from committed benchmark results.

Writes one markdown fragment per entry in ``bench.scorecards.SCORECARDS`` into
``chapters/_generated/``. Chapters include those fragments, so every figure in the book traces
back to a stamped result file (PLAN.md §6.3).

Usage:
    python3 scripts/render-scorecards.py            # write fragments
    python3 scripts/render-scorecards.py --check    # fail if any committed fragment is stale
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from bench.scorecard import (  # noqa: E402
    arithmetic_table,
    attention_footprint_table,
    chunk_cost_table,
    conditions,
    handoff_table,
    kv_quantisation_table,
    memory_table,
    outlier_table,
    quantisation_table,
    score_matrix_table,
    table,
)
from bench.scorecards import CONDITIONS, SCORECARDS  # noqa: E402

OUT_DIR = ROOT / "chapters" / "_generated"

BANNER = "<!-- Generated by scripts/render-scorecards.py. Do not edit by hand. -->"


#: fragments that are computed rather than tabulated from a single result set
DERIVED = {
    "ch03-arithmetic": lambda: arithmetic_table("cached-rate1-tier1", "naive-rate1-tier1"),
    "ch08-memory": memory_table,
    "ch10-chunk-cost": chunk_cost_table,
    "ch11-handoff": handoff_table,
    "ch12-footprint": attention_footprint_table,
    "ch12-score-matrix": score_matrix_table,
    "ch14-quantisation": quantisation_table,
    "ch14-kv-quantisation": kv_quantisation_table,
    "ch14-outliers": outlier_table,
}


def render(name: str) -> str:
    body = DERIVED[name]() if name in DERIVED else table(SCORECARDS[name])
    parts = [BANNER, "", body]
    source = CONDITIONS.get(name)
    if source:
        parts += ["", f"*Conditions: {conditions(source)}*"]
    return "\n".join(parts) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="verify instead of writing")
    args = parser.parse_args()

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    stale: list[str] = []

    for name in sorted({**SCORECARDS, **DERIVED}):
        target = OUT_DIR / f"{name}.md"
        try:
            rendered = render(name)
        except FileNotFoundError as exc:
            print(f"  MISSING RESULT for {name}: {exc}")
            stale.append(name)
            continue

        if args.check:
            current = target.read_text() if target.exists() else ""
            if current != rendered:
                stale.append(name)
                print(f"  STALE: chapters/_generated/{name}.md")
        else:
            target.write_text(rendered)
            print(f"  wrote chapters/_generated/{name}.md")

    if args.check and stale:
        print(
            "\nrender-scorecards: FAILED — "
            f"{len(stale)} fragment(s) out of date. Run scripts/render-scorecards.py."
        )
        return 1
    print(f"\nrender-scorecards: OK ({len(SCORECARDS) + len(DERIVED)} fragment(s))")
    return 0


if __name__ == "__main__":
    sys.exit(main())
